services:
  barcode-webapp:
    build: .
    container_name: barcode-webapp
    ports:
      - "8501:8501"
    volumes:
      - barcode_generator_configs:/app/.barcode-generator-configs
    restart: unless-stopped

volumes:
  barcode_generator_configs:
